/*
 **@file
 *
 *@brief ECE 486 IRR filter code
 *
 *@author ECE486 Lab Group 1
 *@author John Bowen, Jeremy Juybari, Nate McNutt, Annalyse Nichols
 *
 *@date Febuary 2020.
 *
 * Program to flash the board. 
 */

#include "stm32l4xx_hal.h"
#include "stm32l476g_discovery.h"

#include "ece486.h"
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "ece486_biquad.h"

extern FlagStatus KeyPressed;   // Use to detect button presses

int main(void)
{
  int nsamp;
  float *input, *output1, *output2;
  //static float sign=1.0;
  //static int button_count = 0;
  //char lcd_str[8];
  //int M = 40;

  /*
   * Set up ADCs, DACs, GPIO, Clocks, DMAs, and Timer
   *
   * If your discovery board has been modified to support the external
   * HSE reference, use the (better quality crystal controlled) HSE
   * configuration.  If not, you can use the MSI reference, and things
   * should still work -- but your clocks will drift over time.
   *
   * The MSI (Medium speed internal) reference is the on-chip RC oscillator
   *
   * The HSE (High speed external) reference is an external clock, either
   * provided through the external connector, or (if your board is modified)
   * from the crystal reference source generated by the other processor
   * on the development board.
   */
  //initialize_ece486(FS_50K, MONO_IN, STEREO_OUT, MSI_INTERNAL_RC);
  initialize_ece486(FS_48K, MONO_IN, STEREO_OUT, HSE_EXTERNAL_8MHz);

  /*
   * Allocate Required Memory
   */
  nsamp = getblocksize();
  input = (float *)malloc(sizeof(float)*nsamp);
  output1 = (float *)malloc(sizeof(float)*nsamp);
  output2 = (float *)malloc(sizeof(float)*nsamp);
  //float biquad_coefs[] = {1.0, 1.618, 1.0, -1.5371, 0.9025, 1,-.618,1,0,-.81,1,-0.789,1.67, -1.34,0.67};
	float biquad_coefs[] = {
0, 0, 0.25456, -1.13137, 0.64,
3.99779, -6.40388, 3.91824, -1.13137, 0.64,
0.332937, 0.387477, 0.326312, -9.79717e-17, 0.64,
1.83858, -0.909045, 1.17669, -9.79717e-17, 0.64};
	float g = 0.2546;//.0059;
	int sections = 3;

	BIQUAD_T *s = init_biquad(sections, g, biquad_coefs, nsamp);

	if (input==NULL || output1==NULL || output2==NULL) {
    flagerror(MEMORY_ALLOCATION_ERROR);
    while(1);
  }

  /*
   * Normally we avoid printf()... especially once we start actually
   * processing streaming samples.  This is here to illustrate the
   * use of printf for debugging programs.
   *
   * To see the printf output, connect to the ST-Link serial port.
   * Use: 115200 8N1
   */
  printf("Starting execution using %d samples per input block.\n",nsamp);

  /*
   * Infinite Loop to process the data stream, "nsamp" samples at a time
   */
  while(1){
    /*
     * Ask for a block of ADC samples to be put into the working buffer
     *   getblock() will wait here until the input buffer is filled...  On return
     *   we work on the new data buffer... then return here to wait for
     *   the next block
     */
    getblock(input);

    /*
     * signal processing code to calculate the required output buffers
     */

    DIGITAL_IO_SET(); 	// Use a scope on PD0 to measure execution time

    calc_biquad(s, input, output2);

    DIGITAL_IO_RESET();	// (falling edge....  done processing data )

    /*
     * pass the processed working buffer back for DAC output
     */
    putblockstereo(input, output2);

    if (KeyPressed) {
      KeyPressed = RESET;
      //sign *= -1.0;		// Invert output1

      /*
       * On each press, modify the LCD display, and toggle an LED
       * (LED4=red, LED5=green) (Red is used to show error conditions)
       *
       * Don't be surprised when these cause a Sample Overrun error,
       * depending on your sample rate.
       */
      //button_count++;
      //sprintf(lcd_str, "BTN %2d", button_count);
      printf("Button pushed!\n");
      //BSP_LCD_GLASS_DisplayString( (uint8_t *)lcd_str);
      BSP_LED_Toggle(LED5);
    }
  }
  destroy_biquad(s);
}
