/*
 **@file
 *
 *@brief ECE 486 NCO function for implementing on the board.
 *Uses the arm iir biquard function to create a low pass filter
 *
 *@author ECE486 Lab Group 1
 *@author John Bowen, Jeremy Juybari, Nate McNutt, Annalyse Nichols
 *
 *@date April 2020.
 *
 * Program to flash the board.
 */

#include "stm32l4xx_hal.h"
#include "stm32l476g_discovery.h"

#include "ece486.h"
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "ece486_nco.h"
#include <stdint.h>
#include "arm_math.h"
#include <stdint.h>

extern FlagStatus KeyPressed;   // Use to detect button presses

int main(void)
{
  int nsamp,i;
  float *input, *output1, *output2;

  /*
   * Set up ADCs, DACs, GPIO, Clocks, DMAs, and Timer
   *
   * If your discovery board has been modified to support the external
   * HSE reference, use the (better quality crystal controlled) HSE
   * configuration.  If not, you can use the MSI reference, and things
   * should still work -- but your clocks will drift over time.
   *
   * The MSI (Medium speed internal) reference is the on-chip RC oscillator
   *
   * The HSE (High speed external) reference is an external clock, either
   * provided through the external connector, or (if your board is modified)
   * from the crystal reference source generated by the other processor
   * on the development board.
   */
  //initialize_ece486(FS_50K, MONO_IN, STEREO_OUT, MSI_INTERNAL_RC);
  initialize_ece486(FS_50K, MONO_IN, STEREO_OUT, HSE_EXTERNAL_8MHz);

  /*
   * Allocate Required Memory
   */
  nsamp = getblocksize();
  input = (float *)malloc(sizeof(float)*nsamp);
  output1 = (float *)malloc(sizeof(float)*nsamp);
  output2 = (float *)malloc(sizeof(float)*nsamp);

  // Set up NCO waveforms
  NCO_T *s1 = init_nco(0.220115, 0.0); // Initialize NCO structs for 2 waves
  NCO_T *s2 = init_nco(0.220115, 3*M_PI/2);

  s1->amp = 0.99; // Scale factor to not overflow the DAC
  s2->amp = 0.99;

  // Set up IIR filter with coefficients generated from MATLAB
  float arm_biquad_coefs[] = {
    1, 1.72276, 1, 1.11408, -0.396562,
    1, 0.665805, 1, 0.756357, -0.644842,
    1, 0.120679, 1, 0.474834, -0.849113,
    1, -0.0609182, 1, 0.360646, -0.96017
  };

  float32_t g = 0.0128; // Calculated gain factor
  uint8_t numStages = 4; // Number of stages for filtering

  // Apply the filter gain to the first IIR stage coefficients
  arm_biquad_coefs[0] = arm_biquad_coefs[0] * g;
  arm_biquad_coefs[1] = arm_biquad_coefs[1] * g;
  arm_biquad_coefs[2] = arm_biquad_coefs[2] * g;

  // Allocate memory for the ARM IIR filter data pStates
  float32_t *pState = (float32_t *)calloc(2*numStages, sizeof(float32_t));
  float32_t *pState2 = (float32_t *)calloc(2*numStages, sizeof(float32_t));

  // Initialize the ARM IIR filter structs
  arm_biquad_cascade_df2T_instance_f32 armS;
  arm_biquad_cascade_df2T_instance_f32 armS2;

  // Create the ARM IIR filter
  arm_biquad_cascade_df2T_init_f32(&armS, numStages, arm_biquad_coefs, pState);
  arm_biquad_cascade_df2T_init_f32(&armS2, numStages, arm_biquad_coefs,pState2);

  // Check for memory allocation errors
  if (input==NULL||output1==NULL||output2==NULL||pState==NULL||pState2==NULL) {
    flagerror(MEMORY_ALLOCATION_ERROR);
    while(1);
  }

  /*
   * Normally we avoid printf()... especially once we start actually
   * processing streaming samples.  This is here to illustrate the
   * use of printf for debugging programs.
   *
   * To see the printf output, connect to the ST-Link serial port.
   * Use: 115200 8N1
   */
  printf("Starting execution using %d samples per input block.\n",nsamp);
  /*
   * Infinite Loop to process the data stream, "nsamp" samples at a time
   */
  while(1){
    /*
     * Ask for a block of ADC samples to be put into the working buffer
     *   getblock() will wait here until the input buffer is filled...  On return
     *   we work on the new data buffer... then return here to wait for
     *   the next block
     */
    getblock(input);

    /*
     * signal processing code to calculate the required output buffers
     */

    DIGITAL_IO_SET(); 	// Use a scope on PD0 to measure execution time

	// Code to calculate NCO waveform samples
	nco_get_samples(s1, output1, nsamp);
	nco_get_samples(s2, output2, nsamp);

	// Multiply input by 2 NCO waveforms
	for (i = 0; i < nsamp; i++) {
		output1[i] = input[i] * output1[i];
		output2[i] = input[i] * output2[i];
	}

	// Filter to demodulate when viewed in XY mode
	arm_biquad_cascade_df2T_f32(&armS, output1, output1, nsamp);
	arm_biquad_cascade_df2T_f32(&armS2, output2, output2, nsamp);

    DIGITAL_IO_RESET();	// (falling edge....  done processing data )

    /*
     * pass the processed working buffer back for DAC output
     */
    putblockstereo(output1, output2);

  }

}
